- src/Document/CMap/ToUnicode/BFRange.php
> Add support for destination characters that are surrogate pairs

- src/Document/Dictionary/DictionaryEntry/DictionaryEntryFactory.php
- src/Document/Dictionary/DictionaryValue/Array/ArrayValue.php
- src/Document/Dictionary/DictionaryValue/Array/WValue.php
- src/Document/Dictionary/DictionaryValue/Boolean/BooleanValue.php
- src/Document/Dictionary/DictionaryValue/Date/DateValue.php
- src/Document/Dictionary/DictionaryValue/DictionaryValue.php
- src/Document/Dictionary/DictionaryValue/Float/FloatValue.php
- src/Document/Dictionary/DictionaryValue/Integer/IntegerValue.php
- src/Document/Dictionary/DictionaryValue/Rectangle/Rectangle.php
- src/Document/Dictionary/DictionaryValue/Reference/ReferenceValue.php
- src/Document/Dictionary/DictionaryValue/Reference/ReferenceValueArray.php
- src/Document/Dictionary/DictionaryValue/TextString/TextStringValue.php
- tests/Unit/Document/Dictionary/DicitonaryValue/Date/DateValueTest.php
> Simplify dictionary values

- .al-custom.php
- README.md
> Add autoloader for use of this package without Composer

- src/Document/CrossReference/CrossReferenceSourceParser.php
- src/Document/CrossReference/Stream/CrossReferenceStreamParser.php
- src/Document/CrossReference/Table/CrossReferenceTableParser.php
- src/Document/Filter/Decode/FlateDecode.php
- src/Document/Generic/Parsing/RollingCharBuffer.php
- src/Document/Object/Item/CompressedObject/CompressedObjectByteOffsetParser.php
- src/Document/Object/Item/UncompressedObject/UncompressedObject.php
- src/Document/Version/VersionParser.php
- src/Exception/BufferTooSmallException.php
- src/Exception/GzUncompressException.php
- src/Exception/InvalidCrossReferenceLineException.php
- src/Exception/InvalidDictionaryValueTypeFormatException.php
- src/Exception/MarkerNotFoundException.php
- src/Exception/UnsupportedFileFormatException.php
- src/Exception/UnsupportedPdfVersionException.php
- tests/Unit/Document/Version/VersionParserTest.php
> Clean up number of distinct exceptions

- composer.json
- src/Document/Dictionary/DictionaryValue/TextString/TextStringValue.php
- tests/Feature/ParsedResultTest.php
> Add support for text string value bytes

- src/Document/Document.php
- src/Document/Object/Decorator/Annot.php
- src/Document/Object/Decorator/Catalog.php
- src/Document/Object/Decorator/DecoratedObject.php
- src/Document/Object/Decorator/Encoding.php
- src/Document/Object/Decorator/ExtGState.php
- src/Document/Object/Decorator/Font.php
- src/Document/Object/Decorator/FontDescriptor.php
- src/Document/Object/Decorator/GenericObject.php
- src/Document/Object/Decorator/Group.php
- src/Document/Object/Decorator/InformationDictionary.php
- src/Document/Object/Decorator/MarkInfo.php
- src/Document/Object/Decorator/MetaData.php
- src/Document/Object/Decorator/ObjectStream.php
- src/Document/Object/Decorator/Outlines.php
- src/Document/Object/Decorator/Page.php
- src/Document/Object/Decorator/Pages.php
- src/Document/Object/Decorator/StreamObject.php
- src/Document/Object/Decorator/ViewerPreferences.php
- src/Document/Object/Decorator/XObject.php
- src/Document/Object/Decorator/XRef.php
> Cleanup getTypeNameValue from decoratedObjects

- src/Document/Dictionary/DictionaryValue/Name/TabsNameValue.php
> Add new PDF2.0 tabs nameValues

- src/Document/Dictionary/DictionaryParser.php
- src/Document/Dictionary/DictionaryValue/Array/DictionaryArrayValue.php
- tests/Unit/Document/Dictionary/DictionaryParserTest.php
- tests/Unit/Document/Dictionary/DictionaryValue/Array/DictionaryArrayValueTest.php
> Fix issue where nested arrays in dictionaries were closed too early

- src/Document/Dictionary/DictionaryParser.php
- tests/Unit/Document/Dictionary/DictionaryParserTest.php
> Fix comment state in dictionary parsing

- src/Document/Text/TextParser.php
> Fix nesting issues in text operator parsing

- src/Document/Dictionary/DictionaryValue/Name/FilterNameValue.php
> Add missing public key security handlers to FilterNameValue

- src/Document/CMap/Registry/Adobe/Identity0.php
- src/Document/CMap/ToUnicode/CodeSpaceRange.php
- src/Document/CMap/ToUnicode/ToUnicodeCMap.php
- src/Document/CMap/ToUnicode/ToUnicodeCMapParser.php
- tests/Unit/Document/CMap/Registry/Adobe/Identity0Test.php
- tests/Unit/Document/CMap/ToUnicode/ToUnicodeCMapParserTest.php
> Add support for multiple codespaceranges

- src/Document/CrossReference/Stream/CrossReferenceStreamParser.php
- src/Document/Dictionary/DictionaryValue/Name/FilterNameValue.php
- src/Document/Filter/Decode/FlateDecode.php
- src/Document/Object/Item/CompressedObject/CompressedObjectByteOffsetParser.php
- src/Document/Object/Item/CompressedObject/CompressedObjectContent/CompressedObjectContentParser.php
- src/Document/Object/Item/UncompressedObject/UncompressedObject.php
> Remove extra decoding in uncompressed object

- src/Document/Text/OperatorString/TextStateOperator.php
> Allow dashes in font names

- src/Document/Text/TextParser.php
> Fix issues where font operator contains font names

- .github/CONTRIBUTING.md
- .typos.toml
- check hidden files
- "words" are case insensitive
> Fix a typo in CONTRIBUTING

- src/Document/Object/Item/CompressedObject/CompressedObject.php
> Don't try to parse EMCs and other content stream content as dictionaries

- src/Document/ContentStream/PositionedText/PositionedTextElement.php
- src/Document/Object/Decorator/Font.php
> Implement toUnicodeCMap unicode mappings for string literals

- src/Document/ContentStream/ContentStream.php
- tests/Unit/Document/ContentStream/ContentStreamTest.php
- tests/Unit/Document/Text/ContentStreamParserTest.php
> Fix issue when text state is set outside of text object

- README.md
- src/Document/Dictionary/Dictionary.php
- src/Document/Dictionary/DictionaryValue/Name/FilterNameValue.php
- src/Document/Dictionary/DictionaryValue/Name/TypeNameValue.php
- src/Document/Document.php
- src/Document/Image/ImageType.php
- src/Document/Object/Decorator/Page.php
- src/Document/Object/Decorator/XObject.php
- tests/Unit/Document/Dictionary/DictionaryValue/Name/FilterNameValueTest.php
- tests/Unit/Document/Image/ImageTypeTest.php
> Implement image extraction

- src/Document/Document.php
- src/PdfParser.php
- src/Stream/FileStream.php
- src/Stream/InMemoryStream.php
> Make classes non-final to open them for extension and mocking

- src/Document/CrossReference/Table/CrossReferenceTableParser.php
> Don't assume newline after trailer marker,

- composer.json
- src/Document/Dictionary/DictionaryKey/DictionaryKey.php
- src/Document/Dictionary/DictionaryValue/Name/CIEColorSpaceNameValue.php
- src/Document/Dictionary/DictionaryValue/Name/DeviceColorSpaceNameValue.php
- src/Document/Dictionary/DictionaryValue/Name/SpecialColorSpaceNameValue.php
- src/Document/Image/RasterizedImage.php
- src/Document/Object/Decorator/DecoratedObject.php
- src/Document/Object/Decorator/XObject.php
- tests/Manual/LocalSampleTest.php
> Implement rasterized image extraction

- src/Document/Dictionary/DictionaryParser.php
- tests/Unit/Document/Dictionary/DictionaryParserTest.php
> Properly handle newline between dictionary key and value

- src/Document/CrossReference/Stream/CrossReferenceStreamParser.php
> Use the length from a crossReferenceStream when it is available

- src/Document/Object/Decorator/XObject.php
> Add support for array filters in images

- src/Document/CrossReference/CrossReferenceSourceParser.php
> Accept space after byte offset last crossReference source

- src/Document/ContentStream/Command/Operator/State/GraphicsStateOperator.php
> Increase logging for incorrect matrix transformation

- src/Document/Dictionary/DictionaryValue/Name/FilterNameValue.php
- src/Document/Filter/Decode/CCITTFaxDecode.php
- src/Document/Filter/Decode/TiffTag.php
- src/Document/Object/Item/CompressedObject/CompressedObjectContent/CompressedObjectContentParser.php
> Add support for TIFF images (CCITTFaxDecode)

- src/Document/Dictionary/Dictionary.php
- src/Document/Dictionary/DictionaryValue/Array/DictionaryArrayValue.php
- src/Document/Dictionary/DictionaryValue/Name/FilterNameValue.php
- src/Document/Object/Item/CompressedObject/CompressedObjectContent/CompressedObjectContentParser.php
- src/Document/Object/Item/UncompressedObject/UncompressedObject.php
> Accept subdictionary for decodeParams

- src/Document/ContentStream/Command/Operator/State/TextStateOperator.php
- src/Document/ContentStream/PositionedText/TextState.php
> Accept scale values that are floats besides ints

- src/Document/Image/RasterizedImage.php
> Add support for CMYK rasterized images

- src/Document/Filter/Decode/FlateDecode.php
> Add fallback gz decode mechanism when gz headers are missing

- src/Document/Object/Item/UncompressedObject/UncompressedObject.php
- src/Stream/Stream.php
> Properly retrieve content from uncompressed objects

- src/Document/Filter/Decode/FlateDecode.php
> Unlink temp decoding file

- src/Document/Dictionary/DictionaryValue/Name/FilterNameValue.php
@PrinsFrank Why not be beautiful?
> Use printf in exception message

- src/Document/Encryption/RC4.php
- src/Document/Object/Item/CompressedObject/CompressedObjectContent/CompressedObjectContentParser.php
- src/Document/Security/StandardSecurity.php
- tests/Unit/Document/Encryption/RC4Test.php
> Implement decryption when file encryption key is valid

- src/Document/ContentStream/Command/Operator/State/TextStateOperator.php
- tests/Unit/Document/ContentStream/Command/Operator/State/TextStateOperatorTest.php
> Allow font operand to contain plus symbol

- src/Document/ContentStream/Command/Operator/State/TextPositioningOperator.php
- tests/Unit/Document/ContentStream/Command/Operator/State/TextPositioningOperatorTest.php
> Handle newlines and duplicate whitespace in text positioning operands
